Add func for cd ..

diff --git a/zsh/functions b/zsh/functions
--- a/zsh/functions
+++ b/zsh/functions
@@ -23,6 +23,26 @@ extr () {
     fi
 }
 
+# navigation
+up () {
+  local d=""
+  local limit="$1"
+
+  # Default to limit of 1
+  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
+    limit=1
+  fi
+
+  for ((i=1;i<=limit;i++)); do
+    d="../$d"
+  done
+
+  # perform cd. Show error if cd fails
+  if ! cd "$d"; then
+    echo "Couldn't go up $limit dirs.";
+  fi
+}
+
 # Make dir & cd
 mcd() {
     mkdir -p "$1" && cd "$1"
